In [1]:
import pandas as pd
import ast

In [2]:
df = pd.read_csv("/content/tmdb_5000_movies.csv")
df.head()

,budget,genres,homepage,id,keywords,original_language,original_title,overview,popularity,production_companies,production_countries,release_date,revenue,runtime,spoken_languages,status,tagline,title,vote_average,vote_count
0,237000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://www.avatarmovie.com/,19995,"[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...",en,Avatar,"In the 22nd century, a paraplegic Marine is di...",150.437577,"[{""name"": ""Ingenious Film Partners"", ""id"": 289...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2009-12-10,2787965087,162.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}, {""iso...",Released,Enter the World of Pandora.,Avatar,7.2,11800
1,300000000,"[{""id"": 12, ""name"": ""Adventure""}, {""id"": 14, ""...",http://disney.go.com/disneypictures/pirates/,285,"[{""id"": 270, ""name"": ""ocean""}, {""id"": 726, ""na...",en,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...",139.082615,"[{""name"": ""Walt Disney Pictures"", ""id"": 2}, {""...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2007-05-19,961000000,169.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,"At the end of the world, the adventure begins.",Pirates of the Caribbean: At World's End,6.9,4500
2,245000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://www.sonypictures.com/movies/spectre/,206647,"[{""id"": 470, ""name"": ""spy""}, {""id"": 818, ""name...",en,Spectre,A cryptic message from Bond’s past sends him o...,107.376788,"[{""name"": ""Columbia Pictures"", ""id"": 5}, {""nam...","[{""iso_3166_1"": ""GB"", ""name"": ""United Kingdom""...",2015-10-26,880674609,148.0,"[{""iso_639_1"": ""fr"", ""name"": ""Fran\u00e7ais""},...",Released,A Plan No One Escapes,Spectre,6.3,4466
3,250000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 80, ""nam...",http://www.thedarkknightrises.com/,49026,"[{""id"": 849, ""name"": ""dc comics""}, {""id"": 853,...",en,The Dark Knight Rises,Following the death of District Attorney Harve...,112.312950,"[{""name"": ""Legendary Pictures"", ""id"": 923}, {""...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2012-07-16,1084939099,165.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,The Legend Ends,The Dark Knight Rises,7.6,9106
4,260000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://movies.disney.com/john-carter,49529,"[{""id"": 818, ""name"": ""based on novel""}, {""id"":...",en,John Carter,"John Carter is a war-weary, former military ca...",43.926995,"[{""name"": ""Walt Disney Pictures"", ""id"": 2}]","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2012-03-07,284139100,132.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,"Lost in our world, found in another.",John Carter,6.1,2124

In [3]:
movies = df[['title', 'genres', 'popularity', 'vote_average']]
movies.head()

,title,genres,popularity,vote_average
0,Avatar,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",150.437577,7.2
1,Pirates of the Caribbean: At World's End,"[{""id"": 12, ""name"": ""Adventure""}, {""id"": 14, ""...",139.082615,6.9
2,Spectre,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",107.376788,6.3
3,The Dark Knight Rises,"[{""id"": 28, ""name"": ""Action""}, {""id"": 80, ""nam...",112.312950,7.6
4,John Carter,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",43.926995,6.1

In [4]:
def clean_genres(x):
    genres = []
    for i in ast.literal_eval(x):
        genres.append(i['name'])
    return " ".join(genres)

movies['genres'] = movies['genres'].apply(clean_genres)
movies.head()

/tmp/ipykernel_4354/492189272.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  movies['genres'] = movies['genres'].apply(clean_genres)

,title,genres,popularity,vote_average
0,Avatar,Action Adventure Fantasy Science Fiction,150.437577,7.2
1,Pirates of the Caribbean: At World's End,Adventure Fantasy Action,139.082615,6.9
2,Spectre,Action Adventure Crime,107.376788,6.3
3,The Dark Knight Rises,Action Crime Drama Thriller,112.312950,7.6
4,John Carter,Action Adventure Science Fiction,43.926995,6.1

In [5]:
top_rated = movies.sort_values(by='vote_average', ascending=False).head(10)
top_rated

,title,genres,popularity,vote_average
4662,Little Big Top,Comedy,0.092100,10.0
3519,Stiff Upper Lips,Comedy,0.356495,10.0
4045,"Dancer, Texas Pop. 81",Comedy Drama Family,0.376662,10.0
4247,Me You and Five Bucks,Romance Comedy Drama,0.094105,10.0
3992,Sardaarji,,0.296981,9.5
2386,One Man's Hero,Western Action Drama History,0.910529,9.3
1881,The Shawshank Redemption,Drama Crime,136.747729,8.5
2970,There Goes My Baby,Drama Comedy,0.037073,8.5
3337,The Godfather,Drama Crime,143.659698,8.4
2796,The Prisoner of Zenda,Adventure Drama Romance,4.021389,8.4

In [6]:
popular_movies = movies.sort_values(by='popularity', ascending=False).head(10)
popular_movies

,title,genres,popularity,vote_average
546,Minions,Family Animation Adventure Comedy,875.581305,6.4
95,Interstellar,Adventure Drama Science Fiction,724.247784,8.1
788,Deadpool,Action Adventure Comedy,514.569956,7.4
94,Guardians of the Galaxy,Action Science Fiction Adventure,481.098624,7.9
127,Mad Max: Fury Road,Action Adventure Science Fiction Thriller,434.278564,7.2
28,Jurassic World,Action Adventure Science Fiction Thriller,418.708552,6.5
199,Pirates of the Caribbean: The Curse of the Bla...,Adventure Fantasy Action,271.972889,7.5
82,Dawn of the Planet of the Apes,Science Fiction Action Drama Thriller,243.791743,7.3
200,The Hunger Games: Mockingjay - Part 1,Science Fiction Adventure Thriller,206.227151,6.6
88,Big Hero 6,Adventure Family Animation Action Comedy,203.734590,7.8

In [7]:
def recommend_by_genre(genre):
    result = movies[movies['genres'].str.contains(genre, case=False, na=False)]
    return result.sort_values(by='vote_average', ascending=False).head(10)

In [15]:
genre_input = input("Enter a genre (Action, Comedy, Drama, Romance, etc.): ")
recommend_by_genre(genre_input)

Enter a genre (Action, Comedy, Drama, Romance, etc.): comedy

                         title                genres  popularity  vote_average
4247     Me You and Five Bucks  Romance Comedy Drama    0.094105          10.0
3519          Stiff Upper Lips                Comedy    0.356495          10.0
4662            Little Big Top                Comedy    0.092100          10.0
4045     Dancer, Texas Pop. 81   Comedy Drama Family    0.376662          10.0
2970        There Goes My Baby          Drama Comedy    0.037073           8.5
809               Forrest Gump  Comedy Drama Romance  138.133331           8.2
4238              Modern Times          Drama Comedy   28.276480           8.1
3906             The Apartment  Comedy Drama Romance   22.889294           8.1
3041                Love Jones  Comedy Drama Romance    1.000178           8.1
1532  The Grand Budapest Hotel          Comedy Drama   74.417456           8.0